export let vehicleInfo = {
	setupInfoLine: "Welcome - First Time Setup Wizard",
	firstTimeSetup: false,
	vinDecode: false,
	setupStep: 0,
	CCFID: "-",
	As_Built: "",
	VIN: "-",
	Model_id: "-",
	Brand: "-",
	Model: "-",
	ModelName: "-",
	Market: "-",
	BodyStyle: "-",
	Trim: "-",
	Emission: "-",
	ModelYear: "-",
	Plant: "-",
	Driver: "-",
	Transmission: "-",
	Engine: "-",
};

export let vehicleInfoPrev = {
	setupInfoLine: "Welcome - First Time Setup Wizard",
	firstTimeSetup: false,
	vinDecode: false,
	setupStep: 0,
	CCFID: "-",
	As_Built: "",
	VIN: "",
	model_id: "",
	Brand: "",
	Model: "",
	ModelName: "",
	Market: "",
	BodyStyle: "",
	Trim: "",
	Emission: "",
	ModelYear: "",
	Plant: "",
	Driver: "",
	Transmission: "",
	Engine: "",
};
