name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - { electron_builder: "armv7l", docker_buildx: "linux/arm/v7" }
          - { electron_builder: "arm64", docker_buildx: "linux/arm64" }
          - { electron_builder: "x64", docker_buildx: "linux/amd64" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Electron App with Docker
        run: |
          docker buildx build --platform ${{ matrix.platform.docker_buildx }} -t my-electron-app:latest --build-arg BUILD_ARCH=${{ matrix.platform.electron_builder }} -f dockerfile --load .

      - name: Extract AppImage from Docker Image
        run: |
          # This step assumes that your Docker build outputs an AppImage in the /output directory of the container
          id=$(docker create my-electron-app:latest)
          docker cp $id:/output/FLos-${{ matrix.platform.electron_builder }}.AppImage .
          docker rm -v $id

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FLos-${{ matrix.platform.electron_builder }}.AppImage
          path: FLos-${{ matrix.platform.electron_builder }}.AppImage
